### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12969]
There seems to be an issue with the PO import? http://build.berkeleybop.org/job/release-go/218/console

2017-01-29 02:21:20,557 ERROR (CommandRunner:691) Will not proceed until dangling axioms removed, or -n or -f options are set
Exception in thread "main" java.lang.Exception: Dangling axioms will be lost
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:692)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Makefile:171: recipe for target 'po_import.owl' failed
make: *** [po_import.owl] Error 1
Build step 'Execute shell' marked build as failure

**Comment by cmungall** [comment]
r38482, adds `-f` flag

(this obscurity will vanish when we switch to github and a conventional robot pipeline)

**Comment by kltm** [comment]
I'm taking this as a "fixed" and am starting to rebuild.

**Comment by mcourtot** [comment]
Fixed: release-go - Build # 220 - Fixed: Check console output at http://build.berkeleybop.org/job/release-go/220/ to view the results.
