### ISSUE TITLE
Load of go-plus.owl fails while importing uberon_import.owl

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#13286]
For the past couple of nights our ontology update pipeline has failed with the following error:

java -jar /ebi/production/goa/go/bin/OBOParser.jar GO /ebi/production/goa/go/goc-svn/ontology/extensions/go-plus.owl go_xp.raw Y
2017-04-03 02:16:46,236 INFO  (ParserWrapper:71) Start loading ontology: file:/ebi/production/goa/go/goc-svn/ontology/extensions/go-plus.owl from: file:/ebi/production/goa/go/goc-svn/ontology/extensions/go-plus.owl
2017-04-03 02:16:46,451 INFO  (ParserWrapper:71) Start loading ontology: http://purl.obolibrary.org/obo/go/imports/uberon_import.owl from: http://purl.obolibrary.org/obo/go/imports/uberon_import.owl
2017-04-03 02:16:47,164 INFO  (ParserWrapper:78) Finished loading ontology: null from: http://purl.obolibrary.org/obo/go/imports/uberon_import.owl
2017-04-03 02:16:47,165 INFO  (ParserWrapper:78) Finished loading ontology: null from: file:/ebi/production/goa/go/goc-svn/ontology/extensions/go-plus.owl
Exception in thread "main" org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/go/imports/uberon_import.owl> Cause: http://geneontology.org/ontology/imports/uberon_import.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1264)
	at org.coode.owlapi.rdfxml.parser.TPImportsHandler.handleTriple(TPImportsHandler.java:89)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.handleStreaming(OWLRDFConsumer.java:1770)
	at org.coode.owlapi.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1729)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.statementWithResourceValue(RDFParser.java:469)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$EmptyPropertyElement.startElement(RDFParser.java:908)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser$PropertyElementList.startElement(RDFParser.java:801)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.startElement(RDFParser.java:208)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser$1.startElement(RDFXMLParser.java:91)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.semanticweb.owlapi.rdf.syntax.RDFParser.parse(RDFParser.java:135)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:119)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:206)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:829)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:749)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:707)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:254)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:241)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:131)
	at owltools.io.ParserWrapper.parseToOWLGraph(ParserWrapper.java:119)
	at uk.ac.ebi.goa.oboparser.OBOParser.main(OBOParser.java:138)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: http://geneontology.org/ontology/imports/uberon_import.owl
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:214)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:829)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:749)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1224)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1257)
	... 32 more
Caused by: java.io.FileNotFoundException: http://geneontology.org/ontology/imports/uberon_import.owl
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:187)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:153)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:227)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:118)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:206)
	... 36 more
Caused by: java.io.FileNotFoundException: http://geneontology.org/ontology/imports/uberon_import.owl
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:131)
	... 39 more
make: *** [go_xp.raw] Error 1

**Comment by mah11** [comment]
The latest PomBase GAF update (earlier today) has also failed Jenkins checks, apparently for the same reason.

**Comment by cmungall** [comment]
I have a fix ready to go, but can't use svn in-flight it seems...

**Comment by tonysawfordebi** [comment]
Still appears to be broken.

**Comment by cmungall** [comment]
I'm  pretty sure this is fixed now - @tonysawfordebi @mah11 ?

**Comment by ValWood** [comment]
@mah11 is out of office 
@ kimrutherford may know sooner

**Comment by mah11** [comment]
Last time the Jenkins checks ran on the PomBase GAF (26-Apr-2017 15:16) all succeeded, so by the only symptom I saw it looks fixed.

**Comment by pgaudet** [comment]
Closing this since it was reported fix > 1 year ago.
