### ISSUE TITLE
Exception processing latest go-plus.owl with owltools

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/go-ontology#17263]

**Comment by kimrutherford** [comment]
Hi.

We've noticed that the latest go-plus.owl can't be processed by owltools.  The version from before Saturday or so were fine.  We're getting the file from http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

If this is an owltools problem I'll open an issue there.

Thanks!

```
owltools go-plus.owl -o -f obo out-file.obo                                                                                            
Exception in thread "main" org.semanticweb.owlapi.model.OWLOntologyStorageException: org.obolibrary.oboformat.model.FrameStructureException: multiple name tags not allowed. in frame:Frame(CHEBI:67208 id( CHEBI:67208)def( A double stranded ribonucleic acid.)synonym( double stranded ribonucleic acid RELATED)name( double-stranded RNA)name( dsRNA)is_a( CHEBI:33697)is_a( CHEBI:23367))
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:90)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:155)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:119)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1525)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1502)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:289)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:209)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3712)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: org.obolibrary.oboformat.model.FrameStructureException: multiple name tags not allowed. in frame:Frame(CHEBI:67208 id( CHEBI:67208)def( A double stranded ribonucleic acid.)synonym( double stranded ribonucleic acid RELATED)name( double-stranded RNA)name( dsRNA)is_a( CHEBI:33697)is_a( CHEBI:23367))
        at org.obolibrary.oboformat.model.Frame.checkMaxOneCardinality(Frame.java:424)
        at org.obolibrary.oboformat.model.Frame.check(Frame.java:405)
        at org.obolibrary.oboformat.model.OBODoc.check(OBODoc.java:390)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:183)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        ... 11 more
[Exit 1 ]
```

**Comment by balhoff** [comment]
There was a change that is probably the cause of this: https://github.com/geneontology/go-announcements/issues/56

I assume it's because there is content in the file now that was previously not saved to OBO, since it was in an external import.

@cmungall is there an owltools option that will let this through?

**Comment by balhoff** [comment]
In the meantime I will try to see why we're getting two labels.

**Comment by balhoff** [comment]
The extra label is coming from the PRO import.

**Comment by balhoff** [comment]
@kimrutherford out of curiosity do you require OBO format for the next step in your workflow? If you save to OWL instead you shouldn't have an issue.

**Comment by kimrutherford** [comment]
Unfortunately our workflow depends on OBO.

**Comment by balhoff** [comment]
I've got a fix for the double CHEBI labels coming from PRO. However then this reveals that the OBA import contains double labels for OBA terms, which is actually that way in OBA. Will try to sort that out next.

**Comment by balhoff** [comment]
@kimrutherford I just realized there is a `--no-check` option for owltools:

`owltools go-plus.owl -o -f obo --no-check out-file.obo`

should succeed. The question then is whether multiple labels causes you any other problems.

**Comment by kimrutherford** [comment]
> I just realized there is a --no-check option for owltools

That works.  Thanks!

> The question then is whether multiple labels causes you any other problems.

It looks like it's all fine.

**Comment by ukemi** [comment]
Looks like this is solved. If the issue persists, please reopen.
