### ISSUE TITLE
Strange error occurs during ontology build

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#21468]
When building the ontology with 

```
make RELEASEDATE=$START_DATE OBO=http://purl.obolibrary.org/obo ROBOT_ENV="ROBOT_JAVA_ARGS=-Xmx48G" all
make prepare_release
```

The following error (non-fatal) shows up:

```
4:50:52  http://purl.obolibrary.org/obo/CHEBI_136721 ## telomeric repeat-containing RNA
14:50:52   running reasoner 
14:50:52   exporting 
14:51:19  writing n triples: 1794347
14:51:51  Exception in thread "main" java.io.FileNotFoundException: /Users/benjamingood/gocam_ontology/REO/promapping.txt (No such file or directory)
14:51:51  	at java.base/java.io.FileInputStream.open0(Native Method)
14:51:51  	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
14:51:51  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
14:51:51  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
14:51:51  	at java.base/java.io.FileReader.<init>(FileReader.java:60)
14:51:51  	at org.geneontology.gocam.exchange.PRO.readReact2PRO(PRO.java:106)
14:51:51  	at org.geneontology.gocam.exchange.PhysicalEntityOntologyBuilder.countPhysical(PhysicalEntityOntologyBuilder.java:1064)
14:51:51  	at org.geneontology.gocam.exchange.PhysicalEntityOntologyBuilder.buildReacto(PhysicalEntityOntologyBuilder.java:407)
14:51:51  	at org.geneontology.gocam.exchange.Biopax2GOCmdLine.main(Biopax2GOCmdLine.java:106)
14:51:51  
```

This does seem to be non-fatal and things still *seem* to build fine, but I was wondering if this is a "safe" oops or might be worth exploring?

Tagging @balhoff, @sierra-moxon (original reporter)

**Comment by pgaudet** [comment]
Has this been fixed ?

**Comment by balhoff** [comment]
I believe this was fixed by a new biopax2go by @dustine32. I don't see it in the output anymore.
